#!/usr/bin/env python3
"""Generate the compact vanilla English/Chinese recipe-name alias table."""

from __future__ import annotations

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts-raw/languages/chinese_s.po"
TARGET = ROOT / "scripts/dst-controller/crafting/recipe-aliases.lua"


def parse_po(path: Path) -> list[tuple[str, str, str]]:
    entries: list[tuple[str, str, str]] = []
    context = msgid = msgstr = None
    field = None

    def flush() -> None:
        nonlocal context, msgid, msgstr, field
        prefix = "STRINGS.NAMES."
        if context and context.startswith(prefix) and msgid and msgstr:
            entries.append((context[len(prefix) :], msgid, msgstr))
        context = msgid = msgstr = field = None

    for raw_line in [*path.read_text(encoding="utf-8-sig").splitlines(), ""]:
        if not raw_line:
            flush()
        elif raw_line.startswith("msgctxt "):
            context = ast.literal_eval(raw_line[8:])
            field = "context"
        elif raw_line.startswith("msgid "):
            msgid = ast.literal_eval(raw_line[6:])
            field = "msgid"
        elif raw_line.startswith("msgstr "):
            msgstr = ast.literal_eval(raw_line[7:])
            field = "msgstr"
        elif raw_line.startswith('"'):
            value = ast.literal_eval(raw_line)
            if field == "context":
                context = (context or "") + value
            elif field == "msgid":
                msgid = (msgid or "") + value
            elif field == "msgstr":
                msgstr = (msgstr or "") + value

    return entries


def lua_quote(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def main() -> None:
    lines = [
        "-- Generated by tools/generate_recipe_aliases.py; do not edit manually.",
        "-- English and Simplified Chinese aliases from the bundled DST reference PO.",
        "return {",
    ]
    for key, english, chinese in sorted(parse_po(SOURCE)):
        lines.append(
            f"    [{lua_quote(key)}] = "
            f"{{{lua_quote(english)}, {lua_quote(chinese)}}},"
        )
    lines.extend(["}", ""])
    TARGET.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
